# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: init hexo & build
      run: | 
        # sudo npm install hexo-cli -g 
        # npm install
        # npm run clean
        # npm run build
        cd public
        ls
        

    # npm install hexo-cli 
    # Runs a set of commands using the runners shell
   
    # deploy
   
    # - uses: manyuanrong/setup-ossutil@v1.0
    #   with:
    #     # endpoint 可以去oss控制台上查看
    #     endpoint: "oss-cn-hangzhou.aliyuncs.com"
    #     # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
    #     access-key-id: ${{ secrets.ACCESS_KEY_ID }}
    #     access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    

    # Runs a set of commands using the runners shell
    - name: deploy to aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    # - name: cp files to aliyun
    #   run: ossutil cp -rf ./ oss://jncons/

    - name: Deply To OSS
      run: ossutil cp public oss://ysj-website/ -rf
